/**
 * SpecAd — composition that turns an AdSpec into a rendered ad by
 * assembling the 8 primitives in remotion/src/primitives/.
 *
 * Pure presentation: the composition takes a spec, reads its fields,
 * and arranges the primitives. No business logic, no AI, no I/O.
 *
 * Phase 3 of the spec-driven migration. Lives entirely alongside the
 * legacy AdvertiserAd composition. Once Phase 5 A/B testing confirms
 * visual parity (or improvement) we'll switch the production render
 * pipeline to use SpecAd, then retire the hardcoded AdvertiserAd
 * styles in Phase 7.
 *
 * The Studio preview default-spec is generated by `generateSpec` so
 * the same code path used in production also feeds the dev preview —
 * easy to spot regressions while editing primitives.
 */

import React from "react";
import { AbsoluteFill } from "remotion";
import type { AdSpec, EntryAnimation } from "./specs";
import { generateSpec } from "./specs";
import {
  PhotoBackground,
  GradientOverlay,
  EntryFlash,
  AccentLine,
  Headline,
  Tagline,
  CTABox,
  ContentLayout,
} from "./primitives";

export interface SpecAdProps {
  spec?: AdSpec;
}

// ── Default spec for Studio preview ─────────────────────────────────────────
// Generated from sample inputs so opening Remotion Studio shows a
// representative ad. The render scripts override this with a real spec.
const DEFAULT_SPEC: AdSpec = generateSpec({
  advertiserId: "studio-preview",
  businessName: "Mi Negocio",
  category: "barber",
  tagline: "Calidad y servicio",
  cta: "Visítanos",
  photoUrl: "",
  format: "horizontal",
});

// ── Helpers ─────────────────────────────────────────────────────────────────
const ALIGN_SELF: Record<"left" | "center" | "right", "flex-start" | "center" | "flex-end"> = {
  left:   "flex-start",
  center: "center",
  right:  "flex-end",
};

// Tagline primitive doesn't accept "type-on" (looks awkward on tagline-
// length text). The spec generator already maps headline-type-on to
// fade-up for the tagline, but we double-guard here for safety so any
// hand-crafted spec that slips through still renders.
function safeTaglineEntry(entry: EntryAnimation): Exclude<EntryAnimation, "type-on"> {
  return entry === "type-on" ? "fade-up" : entry;
}

// ── Component ───────────────────────────────────────────────────────────────
export const SpecAd: React.FC<SpecAdProps> = ({ spec = DEFAULT_SPEC }) => {
  const ctaAlign = ALIGN_SELF[spec.layout.alignment];

  return (
    <AbsoluteFill style={{ backgroundColor: "#000", overflow: "hidden" }}>
      {/* Photo + camera motion */}
      <PhotoBackground
        url={spec.photo.url}
        motion={spec.photo.motion}
        zoomTo={spec.photo.zoomTo}
      />

      {/* Gradient overlay between photo and content */}
      <GradientOverlay gradient={spec.tokens.overlay} />

      {/* Optional intro flash (high-energy families) */}
      {spec.intro && (
        <EntryFlash color={spec.intro.color} duration={spec.intro.duration} />
      )}

      {/* Bottom-aligned content stack */}
      <ContentLayout alignment={spec.layout.alignment} padding={spec.layout.padding}>
        <AccentLine
          color={spec.tokens.accentColor}
          width={spec.accentLine.width}
          height={spec.accentLine.height}
          delay={spec.accentLine.delay}
          position={spec.accentLine.position}
        />

        <Headline
          text={spec.headline.text}
          fontFamily={spec.tokens.fontFamily}
          fontSize={spec.headline.fontSize}
          fontWeight={spec.headline.fontWeight}
          fontStyle={spec.headline.fontStyle}
          textTransform={spec.headline.textTransform}
          letterSpacing={spec.headline.letterSpacing}
          color={spec.tokens.textColor}
          entry={spec.headline.entry}
          delay={spec.headline.delay}
          springConfig={spec.headline.springConfig}
        />

        {spec.tagline && (
          <Tagline
            text={spec.tagline.text}
            fontFamily={spec.tokens.fontFamily}
            fontSize={spec.tagline.fontSize}
            fontWeight={spec.tagline.fontWeight}
            fontStyle={spec.tagline.fontStyle}
            textTransform={spec.tagline.textTransform}
            letterSpacing={spec.tagline.letterSpacing}
            color={spec.tokens.textColor}
            entry={safeTaglineEntry(spec.tagline.entry)}
            delay={spec.tagline.delay}
          />
        )}

        <CTABox
          text={spec.cta.text}
          accentColor={spec.cta.accentColor}
          style={spec.cta.style}
          borderRadius={spec.cta.borderRadius}
          bgAlpha={spec.cta.bgAlpha}
          delay={spec.cta.delay}
          fontSize={spec.cta.fontSize}
          alignSelf={ctaAlign}
        />
      </ContentLayout>
    </AbsoluteFill>
  );
};
